var assetType = [
    {
        "name":"Maquinaria amarilla",
        "di": 0.25,
        "months": 24,
        "dc": 0.40,
        "dm": 1.0,
        "vue": 10,
        "inf": "El valor de la <b>maquinaria amarilla</b> depende principalmente de las horas de las horas de uso, porque lo que se recomienda el método de unidades de producción (en este caso horas). Para este tipo de equipo es importante el tener acceso a un sistema que permita controlar las horas de uso conforme el cliente trabaje el equipo. Con esta maquinaria se debe tener en cuenta su peso operativo y dimensiones, para garantizar que esta tenga un mercado secundario.",
    },
    {
        "name":"Maquinaria agrícola",
        "di": 0.10,
        "months": 12,
        "dc": 0.30,
        "dm": 1.0,
        "vue": 10,
        "inf": "El valor de la <b>maquinaria agrícola</b> depende principalmente de las horas de las horas de uso y su fabricante, porque lo que se recomienda el método de unidades de producción (en este caso horas). Equipos como tractores conforman principalmente este segmento. Son equipos que comúnmente poseen una baja rotación, por lo que no existe un fuerte mercado secundario para estos equipos. Los fabricantes principales son CASE, John Deere, Massey Ferguson, Kubota, entre otros.",
    },
    {
        "name":"Vehículos",
        "di": 0.20,
        "months": 12,
        "dc": 0.28,
        "dm": 0.87,
        "vue": 6,
        "inf": "El valor de los <b>vehículos partículares</b> depende principalmente del tipo de vehículo y su fabricante. Vehículos de fabricantes asiáticos como Toyota, Mazda, Isuzu y Hyundai tienen un fuerte mercado secundario. Con estos bienes es importante tener en cuenta el propósito y uso que tendrá el vehículo ya que su depreciación es alta.",
    },
    {
        "name":"Transporte de carga",
        "di": 0.15,
        "months": 12,
        "dc": 0.20,
        "dm": 0.90,
        "vue": 15,
    },
    {
        "name":"Equipo de computo",
        "di": 0.30,
        "months": 12,
        "dc": 0.44,
        "dm": 1.0,
        "vue": 5,
    },
    {
        "name":"Equipo electrónico",
        "di": 0.40,
        "months": 12,
        "dc": 0.50,
        "dm": 1.0,
        "vue": 5,
    },
    {
        "name":"Equipo médico",
        "di": 0.15,
        "months": 24,
        "dc": 0.35,
        "dm": 0.8,
        "vue": 8,
    },
    {
        "name":"Redes de procesamiento de datos",
        "di": 0.20,
        "months": 12,
        "dc": 0.37,
        "dm": 1.0,
        "vue": 5,
    },
    {
        "name":"Software",
        "di": 0.10,
        "months": 12,
        "dc": 0.15,
        "dm": 1.0,
        "vue": 5,
    },
    {
        "name":"Macbooks",
        "di": 0.33,
        "months": 36,
        "dc": 0.55,
        "dm": 0.85,
        "vue": 5,
        "da": 0.17,
        "fp": 0.0152790649144242,
    }
]
